#!/usr/bin/env python

from zensols.cli import CliHarness

if (__name__ == '__main__'):
    harness = CliHarness(
        src_dir_name='src/python',
        package_resource='zensols.mimic',
        proto_args='proto',
        proto_factory_kwargs={'reload_pattern': r'^zensols.mimic'},
    )
    harness.run()
