#!/usr/bin/env python

from zensols.cli import CliHarness

# command line entry point
if (__name__ == '__main__'):
    harness = CliHarness(
        src_dir_name='src/python',
        app_factory_class='zensols.mimic.ApplicationFactory',
        # prototyping arguments
        #proto_args='proto',
        proto_args='note 130992',
        proto_factory_kwargs={'reload_pattern': r'^zensols.mimic.(?:app)'},
    )
    harness.run()
